### ISSUE TITLE
Questions about DST offset setting/handling

### ISSUE THREAD

**Issue by krdyke** [ruthtillman/yaml-generator-for-hathitrust#1]
Hi there,

Thanks for the great script! It's been very helpful for us at Oklahoma State. Looking at the DST offsets, I'm a bit confused on two fronts. I haven't been the one digging into it, but am now trying to help out and can't think this through on my own.

1) To me, offsets of 5 and 6 seem to correspond to Central time rather than Eastern time. At least, looking at a source like the [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). 
2) Going with 5 and 6 as the offsets for Central Daylight/Standard, if DST is in effect, shouldn't the offset then be smaller? Meaning, rather than this:

```python
if DST.lower() == 'yes' or DST.lower() == 'y':
	DSTOffset = '6'
else:
	DSTOffset = '5'
```

It should look like this?

```python
if DST.lower() == 'yes' or DST.lower() == 'y':
	DSTOffset = '5' # like 2017-03-29T18:29:29-05:00
else:
	DSTOffset = '6' # like 2017-03-29T18:29:29-06:00
```

Sorry if I'm totally missing something here. If that's the case, any help as to how to alter the script for Central Time would be greatly appreciated. Thanks again!

**Comment by ruthtillman** [comment]
Yes, you're correct, these would be the wrong numbers /facepalm. Luckily, that's not a huge issue in the big picture but that's embarrassing.

**Comment by krdyke** [comment]
Handling time/timezones always makes my head ache, so there's no embarrassment to be had! I'll go ahead and close this.
